(!) python-3 related bugfix in extract_particle.py: KeysView
Python3 no longer accepts indexing in the keys of a dictionary.
A code like this,

  d = {'a':1, 'b':2}
  d.keys()[0]

produces and error:

  TypeError: 'dict_keys' object does not support indexing

Correct way to do it is list(d.keys())[0]
(credit: Jonah Miller)